# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dQo4wS7lrJYbaM893rGoEjlnMzo-JU0
"""

# ================================================
# EXERCÍCIO 05 - Sistema de Financiamento Bancário
# ================================================
print("\n" + "=" * 37)
print("EXERCÍCIO 05 - Financiamento Bancário")
print("=" * 37)
print()

# --- FUNÇÕES ---

def pode_aprovar(idade, renda, valor):
    # O cliente só é aprovado se tiver mais de 18 anos E
    # o valor pedido for no máximo 20x a renda mensal
    return idade > 18 and valor <= renda * 20

def definir_taxa(parcelas):
    # Define a taxa de juros mensal com base no número de parcelas
    if parcelas <= 6:
        return 0.05    # 5% ao mês
    elif parcelas <= 12:
        return 0.08    # 8% ao mês
    else:
        return 0.10    # 10% ao mês

def calcular_parcela(valor, taxa, parcelas):
    # Fórmula Price (parcelas fixas com juros compostos):
    # PMT = PV * [ i*(1+i)^n ] / [ (1+i)^n - 1 ]
    return valor * (taxa * (1 + taxa) ** parcelas) / ((1 + taxa) ** parcelas - 1)

def calcular_total(parcela, parcelas):
    # Valor total pago = parcela multiplicada pelo número de parcelas
    return parcela * parcelas

def calcular_juros(total, valor):
    # Total de juros = o que foi pago no total menos o que foi emprestado
    return total - valor

# --- ENTRADAS ---
nome_cli  = input("Nome do cliente: ")
idade     = int(input("Idade: "))
renda     = float(input("Renda mensal: R$ "))
valor_emp = float(input("Valor desejado do empréstimo: R$ "))
parcelas  = int(input("Número de parcelas (3 a 24): "))

# --- LÓGICA DE APROVAÇÃO ---
print()
if pode_aprovar(idade, renda, valor_emp):
    # Se aprovado, calcula todos os valores do financiamento
    taxa   = definir_taxa(parcelas)
    pmt    = calcular_parcela(valor_emp, taxa, parcelas)
    total  = calcular_total(pmt, parcelas)
    juros  = calcular_juros(total, valor_emp)

    print("Empréstimo APROVADO!")
    print(f"Cliente:            {nome_cli}")
    print(f"Valor financiado:   R$ {valor_emp:.2f}")
    print(f"Taxa de juros:      {taxa*100:.0f}% ao mês")
    print(f"Valor da parcela:   R$ {pmt:.2f}")
    print(f"Valor total pago:   R$ {total:.2f}")
    print(f"Total de juros:     R$ {juros:.2f}")
else:
    # Se negado, informa qual(is) regra(s) não foram atendidas
    print("Empréstimo NEGADO!")
    if idade <= 18:
        print("Motivo: cliente deve ter mais de 18 anos.")
    if valor_emp > renda * 20:
        print(f"Motivo: valor excede 20x a renda mensal (limite: R$ {renda*20:.2f}).")